Algoritmo "Exercício 6"

Var
salfixo, comissao, vendas, salario_final: real

Inicio
escreval ("Digite o valor do salário fixo:")
leia (salfixo)
escreval ("Digite o valor total de vendas:")
leia (vendas)
comissao <- vendas * 4/100
salario_final <- salfixo + comissao
escreval ("O valor de comissao e de:", comissao)
escreval ("O valor do salário e comissão é de:", salario_final)

Fimalgoritmo